### ISSUE TITLE
what does "t " mean in section "Implementation details 2) CenterNet3D head"

### ISSUE THREAD

**Issue by Beastmaster** [maudzung/CenterNet3D-PyTorch#1]
In your paper, a param t is mentationed in Section "Implementation details 2) CenterNet3D head" : Compared with anchor-based methods ...  To mitigate the imbalance, we set t=0.01 to obtain more...
What is "t "?  

Thank you

**Comment by maudzung** [comment]
Hi @Beastmaster 

Please refer to the official implementation of the paper [here](https://github.com/wangguojun2018/CenterNet3d)
You can raise an issue there also. Thanks
