### ISSUE TITLE
Pretrained Model and Orientation

### ISSUE THREAD

**Issue by Daniel-1597** [maudzung/CenterNet3D-PyTorch#3]
Hi, 
can you provide pretrained model file and there is an issue with the orientation of the model. I have trained it on Kitti Dataset for 200 epochs and the orientation is still wrong Can you tell what can be the reason? I have attached the results as well please go through it.

Thanks and Regards,
Daniel.
![Screenshot from 2021-01-27 10-19-24](https://user-images.githubusercontent.com/53418529/107323572-7ee8f100-6acc-11eb-9be6-2265a4475cad.png)

![Screenshot from 2021-01-27 10-19-36](https://user-images.githubusercontent.com/53418529/107323408-38939200-6acc-11eb-823b-eefb6bd11c46.png)

**Comment by maudzung** [comment]
Hi @Daniel-1597 

Please refer to the official implementation of the paper [here](https://github.com/wangguojun2018/CenterNet3d)
